version: '3'

services:
  postgres:
    container_name: todo-db-pg
    image: postgres:14
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - '.env'